replicaCount: 1
appVersion: sha-904afeb1a49fd2a5701c852112a7b6405c8fdf7e
image:
  repository: ghcr.io/hako-spec1al/k8s-cicd-platform
  tag: sha-904afeb1a49fd2a5701c852112a7b6405c8fdf7e
#keep override
ingress:
  host: platform-dev.local
