replicaCount: 1
appVersion: sha-96b66c6c070fbe91274a19fe87e0641b93b9f3f7
image:
  repository: ghcr.io/hako-spec1al/k8s-cicd-platform
  tag: sha-96b66c6c070fbe91274a19fe87e0641b93b9f3f7
#keep override
ingress:
  host: platform-dev.local
