apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-api
  namespaceSelector:
    matchNames:
      - platform-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s